# Generated by Django 4.2.7 on 2025-11-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_business_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
