# Generated by Django 4.2.7 on 2025-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accessibility_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_preference',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both Email and Phone')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, choices=[('2-hours', '2 Hours'), ('4-hours', '4 Hours'), ('6-hours', '6 Hours'), ('full-day', 'Full Day (8+ Hours)'), ('multi-day', 'Multi-Day Event'), ('custom', 'Custom Duration')], max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_5k', 'Under ₹5,000'), ('5k_15k', '₹5,000 - ₹15,000'), ('15k_30k', '₹15,000 - ₹30,000'), ('30k_50k', '₹30,000 - ₹50,000'), ('over_50k', 'Over ₹50,000')], max_length=20),
        ),
    ]
