# Generated by Django 4.2.7 on 2025-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_accessibility_needs_event_budget_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='adult_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='ceremony_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='Dietary requirements and restrictions'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='inspiration_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='other_milestones',
            field=models.TextField(blank=True, help_text='Other key timings, one per line'),
        ),
        migrations.AddField(
            model_name='event',
            name='reception_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_guests',
            field=models.TextField(blank=True, help_text='VIP guest names, one per line'),
        ),
    ]
