# Generated by Django 4.2.7 on 2025-10-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_adult_count_event_ceremony_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='adult_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ceremony_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='children_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='other_milestones',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reception_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vip_guests',
        ),
        migrations.AddField(
            model_name='event',
            name='timeline',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic timeline events'),
        ),
    ]
