# Generated by Django 4.2.7 on 2025-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_adult_count_remove_event_ceremony_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeline',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic timeline events', null=True),
        ),
    ]
