# Generated by Django 4.2.7 on 2025-10-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='food_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Selected food types and cuisines', null=True),
        ),
    ]
