# Generated by Django 4.2.7 on 2025-10-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventfile_event_delete_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('style_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'events_traditionstyle',
            },
        ),
    ]
