# Generated by Django 4.2.7 on 2025-10-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_selected_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selected_services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
