# Generated by Django 4.2.7 on 2025-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20251013_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='special_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Format: {req_id: {selected: bool, quantity: int, unit: str}}'),
        ),
    ]
