# Generated by Django 4.2.7 on 2025-10-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_selected_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allocation_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'AI-Powered')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_allocation',
            field=models.JSONField(blank=True, default=dict, help_text='Budget allocation by category'),
        ),
    ]
