# Generated by Django 4.2.7 on 2025-10-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_allocation_method_event_budget_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selected_services',
            field=models.JSONField(blank=True, default=list, help_text='List of selected service names'),
        ),
    ]
