# Generated by Django 4.2.7 on 2025-10-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_create_event_system_tables'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventsection',
            name='events_eventsection_section_id_idx',
        ),
        migrations.RenameIndex(
            model_name='eventimage',
            new_name='event_image_event_i_ae77f2_idx',
            old_name='events_eventimage_event_id_idx',
        ),
        migrations.RenameIndex(
            model_name='eventrequirement',
            new_name='event_requi_event_i_a78a31_idx',
            old_name='events_eventrequirement_event_id_idx',
        ),
        migrations.RenameIndex(
            model_name='eventsubsection',
            new_name='event_subse_subsect_a7f44a_idx',
            old_name='events_eventsubsection_subsection_id_idx',
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventrequirement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventsubsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
