# Generated by Django 4.2.7 on 2025-10-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_eventsection_events_eventsection_section_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
