# Generated by Django 4.2.7 on 2025-10-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_create_requirement_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requirementquestion',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_questions', to='events.eventrequirement'),
        ),
        migrations.AlterModelTable(
            name='requirementquestion',
            table='requirement_questions',
        ),
    ]
