# Generated by Django 4.2.7 on 2025-10-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_requirementquestion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=1000)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'requirement_images',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['requirement_id'], name='requirement_require_321ce7_idx')],
            },
        ),
    ]
