# Generated by Django 4.2.7 on 2025-10-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_requirementimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequirementImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('requirement_name', models.CharField(max_length=100)),
                ('image_number', models.IntegerField()),
                ('image_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_requirement_images',
                'ordering': ['event_name', 'requirement_name', 'image_number'],
            },
        ),
    ]
