# Generated by Django 4.2.7 on 2025-10-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_restore_herovideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequirementImage',
        ),
    ]
